# Generated by Django 6.0.1 on 2026-03-05 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(max_length=250)),
                ('street_number', models.IntegerField()),
                ('city', models.CharField(max_length=250)),
                ('person_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend_webapp.person')),
            ],
        ),
    ]
